# Generated by Django 4.2.1 on 2023-06-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('regdate', models.DateTimeField(auto_now=True)),
                ('readcount', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
